// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  "rebalancer": {
    "account": {
      "noAccounts": "No accounts found.",
      "searchPlaceholder": "Search accounts...",
      "select": "Select an account",
      "selectPrompt": "Please select an account to identify transfer opportunities."
    },
    "controls": {
      "any": "Any",
      "decreaseThreshold": "Decrease threshold",
      "increaseThreshold": "Increase threshold",
      "pp": "{{value}}pp",
      "threshold": "Threshold"
    },
    "holdings": {
      "addTransactions": "Add Transactions",
      "empty": "No holdings found in this account."
    },
    "overview": {
      "aboveTarget": "Above target",
      "belowTarget": "Below target",
      "biggestGaps": "Biggest gaps",
      "colAllocation": "Allocation",
      "colCurrent": "Current",
      "colDrift": "Drift",
      "colFund": "Fund",
      "colTarget": "Target",
      "gapsSubtitleAll": "Funds off target, largest deviation first.",
      "gapsSubtitleThreshold": "Funds beyond the {{value}}pp threshold.",
      "subtitleCurrent": "Current allocation of each fund versus its target.",
      "subtitleProjected": "Projected allocation after applying the suggested transfers.",
      "title": "Allocation vs target"
    },
    "plan": {
      "configurePrompt": "Set your target allocations to discover which transfers will bring your portfolio on target.",
      "corrupted": "Your plan needs adjustment. Make sure enabled allocations add up to 100%.",
      "create": "Create Plan",
      "description": "Define your target allocations — the addon will calculate the optimal transfers to reach them.",
      "edit": "Edit Plan"
    },
    "planner": {
      "enableAria": "Enable {{name}} in the plan",
      "save": "Save",
      "saveError": "Failed to save the plan. Please try again.",
      "sumError": "Enabled targets sum to {{total}}%, must equal 100%",
      "targetAria": "Target allocation for {{name}}"
    },
    "transfers": {
      "onTarget": "Your portfolio is on target — no transfers needed.",
      "pctTooltip": "Percentage of the source fund being transferred"
    },
    "view": {
      "current": "Current",
      "projected": "Projected",
      "transfers": "Transfers"
    }
  }
}
